
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

import java.util.LinkedList;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SSimbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public SParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\002\005\000\002\002\005\000\002\002\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\006\016\004\020\005\001\002\000\006\016" +
    "\004\020\005\001\002\000\014\002\ufffc\012\ufffc\013\ufffc" +
    "\014\ufffc\017\ufffc\001\002\000\012\002\011\012\012\013" +
    "\007\014\010\001\002\000\006\016\004\020\005\001\002" +
    "\000\006\016\004\020\005\001\002\000\004\002\001\001" +
    "\002\000\006\016\004\020\005\001\002\000\014\002\000" +
    "\012\000\013\000\014\010\017\000\001\002\000\014\002" +
    "\ufffe\012\ufffe\013\ufffe\014\ufffe\017\ufffe\001\002\000\014" +
    "\002\uffff\012\uffff\013\uffff\014\010\017\uffff\001\002\000" +
    "\012\012\012\013\007\014\010\017\017\001\002\000\014" +
    "\002\ufffd\012\ufffd\013\ufffd\014\ufffd\017\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\004\002\005\001\001\000\004\002\015\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\014" +
    "\001\001\000\004\002\013\001\001\000\002\001\001\000" +
    "\004\002\012\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    LinkedList<String> errores = null;

    public void setErrores(LinkedList<String> lista) {
    }

    public void syntax_error(Symbol s)
    {        
        
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {      
    }

    


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SParser$actions {



  private final SParser parser;

  /** Constructor */
  CUP$SParser$actions(SParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SParser$do_action_part00000000(
    int                        CUP$SParser$act_num,
    java_cup.runtime.lr_parser CUP$SParser$parser,
    java.util.Stack            CUP$SParser$stack,
    int                        CUP$SParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SParser$result;

      /* select the action based on the action number */
      switch (CUP$SParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= E EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.elementAt(CUP$SParser$top-1)).value;
		RESULT = start_val;
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-1)), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SParser$parser.done_parsing();
          return CUP$SParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // E ::= E plus E 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.elementAt(CUP$SParser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.peek()).value;
		 System.out.println("+") ;
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          return CUP$SParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // E ::= E minus E 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.elementAt(CUP$SParser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.peek()).value;
		System.out.println("-") ; 
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          return CUP$SParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // E ::= E mult E 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.elementAt(CUP$SParser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.peek()).value;
		 System.out.println("*") ; 
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          return CUP$SParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // E ::= par_open E par_close 
            {
              String RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-1)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.elementAt(CUP$SParser$top-1)).value;
		 
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.elementAt(CUP$SParser$top-2)), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          return CUP$SParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // E ::= num 
            {
              String RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$SParser$stack.peek()).value;
		System.out.println(s); 
              CUP$SParser$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SParser$stack.peek()), RESULT);
            }
          return CUP$SParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SParser$do_action(
    int                        CUP$SParser$act_num,
    java_cup.runtime.lr_parser CUP$SParser$parser,
    java.util.Stack            CUP$SParser$stack,
    int                        CUP$SParser$top)
    throws java.lang.Exception
    {
              return CUP$SParser$do_action_part00000000(
                               CUP$SParser$act_num,
                               CUP$SParser$parser,
                               CUP$SParser$stack,
                               CUP$SParser$top);
    }
}

}
