
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class SSimbolos {
  /* terminals */
  public static final int nigual = 24;
  public static final int par_close = 13;
  public static final int minus = 9;
  public static final int print = 3;
  public static final int mult = 10;
  public static final int mayor_igu = 21;
  public static final int par_open = 12;
  public static final int or = 22;
  public static final int num = 14;
  public static final int inc = 25;
  public static final int dotcoma = 6;
  public static final int menor_igu = 20;
  public static final int menor = 18;
  public static final int strng = 16;
  public static final int div = 11;
  public static final int igual = 17;
  public static final int EOF = 0;
  public static final int dec = 26;
  public static final int asig = 7;
  public static final int id = 15;
  public static final int iff = 27;
  public static final int error = 1;
  public static final int plus = 8;
  public static final int cor_close = 5;
  public static final int var = 2;
  public static final int cor_open = 4;
  public static final int and = 23;
  public static final int mayor = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "var",
  "print",
  "cor_open",
  "cor_close",
  "dotcoma",
  "asig",
  "plus",
  "minus",
  "mult",
  "div",
  "par_open",
  "par_close",
  "num",
  "id",
  "strng",
  "igual",
  "menor",
  "mayor",
  "menor_igu",
  "mayor_igu",
  "or",
  "and",
  "nigual",
  "inc",
  "dec",
  "iff"
  };
}

